name: GCP Cloud Functions Deploy (Staging)
on:
  push:
    branches:
      - "staging"
      - "feat/mvp"
jobs:
  build-deploy-cloud-function:
    permissions:
      contents: "read"
      id-token: "write"

    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_CREDS_JSON }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - id: "deploy"
        run: >
          gcloud
          functions
          deploy
          shorty-dev
          --gen2
          --region=us-central1
          --source=.
          --runtime=go116
          --trigger-http
          --allow-unauthenticated
          --entry-point=ServeShorty
          --project=operationspark-org
          --set-build-env-vars=GOFLAGS=-mod=mod
          --set-env-vars=MONGO_URI=${{secrets.MONGO_URI}},MONGO_DB_NAME=${{secrets.MONGO_DB_NAME}},API_KEY=${{secrets.API_KEY}},HOST_BASE_URL=${{secrets.HOST_BASE_URL}}
      - id: "trigger-url"
        run: 'echo "${{ steps.deploy.outputs.url }}"'
